### ISSUE TITLE
No objects to concatenate

### ISSUE THREAD

**Issue by CoutinhoElias** [DaviMarta/Automatiza-o#3]
Não sei se é por causa da key mas ao chegar no fim da execução apresenta esta mensagem do título.

![image](https://user-images.githubusercontent.com/12012709/214563871-71a5071c-b187-4e7c-bb2c-7eb2b5dd5224.png)

**Comment by Rigolon** [comment]
Tive o mesmo problema, tinha algumas linhas que estavam comentadas, tem que remover o comentário. É a função csv_to_point:

    def csv_to_point(non_spatial_data):

        #crie o geodataframe e exporte-o como um arquivo de ponto
        del non_spatial_data['Tags']
        spatial_df = gpd.GeoDataFrame(non_spatial_data, geometry=gpd.points_from_xy(non_spatial_data.Longitude, non_spatial_data.Latitude))
        spatial_df.to_csv("point_data.csv")
        print(spatial_df)
        spatial_df.to_file("point_data.shp")

        #create a projection file that corresponds to where data was taken from
        prj = open("point_data.prj", "w")
        epsg = 'GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]'
        prj.write(epsg)
        prj.close()

        return(spatial_df)

**Comment by CoutinhoElias** [comment]
Mesmo assim continuou, acho que tem outros pontos atrapalhando:

Traceback (most recent call last):
  File "c:\Users\EliasPai\Automatiza-o\Web-Scraping Google Maps #1.py", line 163, in <module>
    merged_df = pd.concat(df_list)
  File "C:\Users\EliasPai\kivy_venv\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\EliasPai\kivy_venv\lib\site-packages\pandas\core\reshape\concat.py", line 368, in concat
    op = _Concatenator(
  File "C:\Users\EliasPai\kivy_venv\lib\site-packages\pandas\core\reshape\concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
(kivy_venv) PS C:\Users\EliasPai>

**Comment by CoutinhoElias** [comment]
Pelo visto 

# use compreensão de lista para criar uma lista de arquivos csv
csv_files = [file for file in os.listdir(path) if file.endswith('.csv')]

Não está encontrando nenhum arquivo do tipo CSV, mas existem arquivos no diretório.

**Comment by magskull** [comment]
Não estou conseguindo corrigir o erro informado por vocês.

**Comment by CoutinhoElias** [comment]
De fato o problema era de atenção, no final do código tem o local para onde vão as listas em csv, eu havia adicionado um outro diferente, pós corrigir funcionou.

Pode ser que apareçam outras dúvidas e este canal é muito bom para que outras pessoas possam pesquisar.

Obrigado. 

Encerro.
