### ISSUE TITLE
Como definir o valor de r?

### ISSUE THREAD

**Issue by PatinhoSarrador** [DaviMarta/Automatiza-o#4]
![image](https://user-images.githubusercontent.com/123759295/215266036-1090513b-cefa-47ec-95c4-b414c9e9857b.png)

Nunca mexi com essas coisas, mas dei um jeito de arrumar tudo, porém não descobri como resolver este problema

**Comment by Rigolon** [comment]
O meu ficou da seguinte maneira:

path = r"./excels/"
